name: My first Workflow
on: [push,pull_request]

jobs:
  hello-world:
   runs-on: ubuntu-latest 
   steps: 
    -name: Checkout code 
     uses: actions/checkout@v3
    -name: Say hello
     run: echo"Hello from GitHub Actions!"
    -name: list project files
     run: ls -la
    -name: Show current date
     run: date

